---
new_page_extension: md
auto_deploy: false
admin_path:
webhook_url:
sections:
- type: directory
  path: _documentaries
  label: Documentaries
  create: all
  match: "**/*"
  templates:
  - production
- type: directory
  path: _films
  label: Films
  create: all
  match: "**/*"
  templates:
  - production
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
