---
label: Production
hide_body: false
is_partial: false
fields:
- type: textarea
  name: excerpt
  label: Excerpt
  description: Short text to appear on the banner at the top of the content page.
    No more than 100 words.
- type: number
  name: year
  label: Year of release
- type: text
  name: kind
  label: Kind
  description: The kind of thing that this is, e.g. Feature Film, Short Film
- type: file
  name: video_url
  description: Short video clip to loop in the slide list. It should not start on
    black otherwise iOS users will just get a blank screen.
  label: Homepage video clip
- type: file
  name: poster
  label: Poster
  description: The poster to use on the content page.
- type: field_group_list
  name: trailers
  label: Trailers
  description: |
    Videos you want to include on the content page.
    You can specify where on the content page they appear using the 'Trailer' snippet
    and filling in the name you pick here.
  fields:
  - type: text
    name: name
    label: Name
    description: A descriptive name to help identify the trailer.
  - type: file
    name: file
    label: Video file
    description: The video file to display.
